# Generated by Django 2.2.12 on 2020-06-15 23:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        UnaccentExtension(),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='nombre')),
                ('summary', models.TextField(blank=True, help_text='Describa en pocas palabras su negocio.', verbose_name='descripción')),
                ('avatar', models.ImageField(blank=True, help_text='Logo o imagen de su comercio/negocio. Tamaño máximo: 5MB.', null=True, upload_to='avatars', verbose_name='avatar')),
                ('address', models.CharField(blank=True, help_text='Dirección física de su negocio (calle + número).', max_length=255, verbose_name='dirección')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='longitud | latitud', null=True, srid=4326, verbose_name='coordenadas')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='Facebook')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='email')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='página web')),
                ('has_delivery', models.BooleanField(default=False, help_text='Sólo aplica para comercios.', verbose_name='¿Realiza delivery?')),
                ('is_useful', models.BooleanField(default=False, verbose_name='¿Es número útil?')),
                ('is_visible', models.BooleanField(default=False, verbose_name='¿Es visible?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='valor')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Ejemplo: (02352) 15-123456', max_length=17, verbose_name='número')),
                ('is_whatsapp', models.BooleanField(default=False, help_text='Marcar si es un número de WhatsApp.', verbose_name='¿Es de WhatsApp?')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='businesses.Business')),
            ],
            options={
                'verbose_name': 'número de teléfono',
                'verbose_name_plural': 'números de teléfono',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='tags',
            field=models.ManyToManyField(blank=True, to='businesses.Tag'),
        ),
    ]
