# Generated by Django 2.2.11 on 2020-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion
import michacabuco_admin.pharmacies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'farmacia',
                'verbose_name_plural': 'farmacias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PharmacyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=michacabuco_admin.pharmacies.models.get_default_shift_start, verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fin')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pharmacies.Pharmacy', verbose_name='farmacia')),
            ],
            options={
                'verbose_name': 'turno de farmacia',
                'verbose_name_plural': 'turnos de farmacias',
                'ordering': ('start',),
            },
        ),
    ]
