# Generated by Django 2.2.11 on 2020-04-11 04:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import michacabuco_admin.events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('body', ckeditor.fields.RichTextField(verbose_name='cuerpo')),
                ('image', models.ImageField(blank=True, null=True, upload_to=michacabuco_admin.events.models.event_image_path, verbose_name='imagen promocional')),
                ('youtube', models.URLField(blank=True, help_text='Link a video de YouTube', verbose_name='video promocional (YouTube)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='fin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.Event', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'fecha de evento',
                'verbose_name_plural': 'fechas de evento',
                'ordering': ['start'],
            },
        ),
    ]
